version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db-notifications
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notificationdb
      MYSQL_USER: notificationuser
      MYSQL_PASSWORD: notificationpass
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ../scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - notification-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  networks:
      - notification-network

  notification-service:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    container_name: notification-service
    depends_on:
      - mysql
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/notificationdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: notificationuser
      SPRING_DATASOURCE_PASSWORD: notificationpass
    volumes:
      - notification_logs:/app/logs
    networks:
      - notification-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8082/api/v1/notifications/health"]
      interval: 30s
      timeout: 10s
      start_period: 60s
      retries: 3

volumes:
  mysql_data:
  notification_logs:

networks:
  notification-network:
    driver: bridge