services:
  products-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: productdb
    ports:
      - "3308:3306"
    volumes:
      - /var/lib/mysql
    command:
      - --binlog-format=ROW
      - --server-id=102
      - --log-bin=mysql-bin
      - --binlog-row-image=FULL
      - --gtid-mode=ON
      - --enforce-gtid-consistency=ON