services:
  # Config Database
  database:
    container_name: database
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: db_user
      MYSQL_PASSWORD: Database@Password123
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    command:
      - --binlog-format=ROW
      - --server-id=102
      - --log-bin=mysql-bin
      - --binlog-row-image=FULL
      - --gtid-mode=ON
      - --enforce-gtid-consistency=ON


  # Config For Kafka
  kafka:
    container_name: broker
    image: apache/kafka:3.9.1
    restart: always
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller 
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://broker:9092,EXTERNAL://broker:9094
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER 
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@broker:9093 
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1 
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1 
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1 
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0 
      - KAFKA_LOG_FLUSH_INTERVAL_MESSAGES=1
    ports:
      - "9092:9092"
      - "9094:9094"
  
  # Kafka Visualization:
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    restart: always
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: 'broker'
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'broker:9092'
    ports:
      - "9095:8080"
    depends_on:
      - kafka

  connect:
    container_name: connect
    image: debezium/connect:2.7.3.Final
    restart: always
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: 'broker:9092'
      GROUP_ID: debezium-cluster-prod
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses
      CONFIG_STORAGE_REPLICATION_FACTOR: 1
      OFFSET_STORAGE_REPLICATION_FACTOR: 1
      STATUS_STORAGE_REPLICATION_FACTOR: 1
    depends_on:
      - kafka
      - database
    volumes:
      - ./connectors:/kafka/connectors


  # Config service app: Please run it before run your app
  discovery-client:
    container_name: registry
    build: 
      context: ../discovery-server
      dockerfile: docker/Dockerfile
    restart: always
    ports:
      - "8761:8761"
    volumes:
      - ../discovery-server:/app


  # # Gateway must be run after all services are up in order to register routes correctly
  # gateway:
  #   container_name: gateway
  #   build: 
  #     context: ../docker/gateway
  #     dockerfile: Dockerfile  
  #   restart: always
  #   ports:
  #     - "8080:8080"

  notification-service:
    container_name: notification-service
    build: 
      context: ../notification-service
      dockerfile: docker/Dockerfile  
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      - discovery-client
      - database
      - kafka
    volumes:
      - ../notification-service:/app

  order-service:  
    container_name: order-service
    build: 
      context: ../order-service
      dockerfile: docker/Dockerfile  
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - discovery-client
      - database
      - kafka
    volumes:
      - ../order-service:/app

  payment-service:
    container_name: payment-service
    build: 
      context: ../payment-service
      dockerfile: docker/Dockerfile  
    restart: always
    ports:
      - "8085:8085"
    depends_on:
      - discovery-client
      - database
      - kafka
    volumes:
      - ../payment-service:/app
  
  product-service:
    container_name: product-service
    build: 
      context: ../product-service
      dockerfile: docker/Dockerfile  
    restart: always
    ports:
      - "8084:8084"
    depends_on:
      - discovery-client
      - database
      - kafka
    volumes:
      - ../product-service:/app
